# Nitro configuration
enabled: true # Enable Discord bot?

token: "" # Discord bot token
server: "" # ID of Discord server
nitro-role: "" # ID of the Nitro role

channel-alerts: "" # ID of channel where logs from bot are sent
channel-main: "" # ID of channel where command can be used
channel-staff: "" # ID of channel where staff commands can be used

# List of redemption commands, executed when the user redeems Nitro privileges
redemption-commands:
  - ""

# List of removal commands, executed when the user removes their privileges or stops boosting the server
removal-commands:
  - ""

# List of Nitro boosters
# Format
# Discord username : User Discord ID : Minecraft username : Minecraft username
nitro-boosters:
  - ""
