name: Publish compiled jar to GitHub releases
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Build jar
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: NitroCloudy-1.0.0-SNAPSHOT.jar
          path: target/NitroCloudy-1.0.0-SNAPSHOT.jar

      - name: Move generated jar file
        run: mv target/NitroCloudy-1.0.0-SNAPSHOT.jar NitroCloudy-1.0.0-SNAPSHOT.jar

      - name: Create Release
        id: create_release
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: NitroCloudy-${{github.sha}}
          release_name: Release NitroCloudy-${{github.sha}}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./NitroCloudy-1.0.0-SNAPSHOT.jar
          asset_name: NitroCloudy-1.0.0-SNAPSHOT.jar
          asset_content_type: application/java-archive
